[package]
authors = ["Taryn Hill <taryn@phrohdoh.com>"]
name = "easage"
version = "0.0.1"
license = "MIT"

[dependencies]
byteorder = "1.1.0"
memmap = "0.5.2"
owning_ref = "0.3.3"
walkdir = "1"
clap = { version = "2.26", optional = true }

[[bin]]
name = "easage"
path = "src/bin/easage.rs"
required-features = ["clap"]

[[bin]]
name = "bigpack"
path = "src/bin/bigpack.rs"
required-features = ["clap"]